### ISSUE TITLE
Can't insert the integer type schema @ x-swagger-mongoose/additional-properties.

### ISSUE THREAD

**Issue by AilisObrian** [simonguest/swagger-mongoose#21]
``` yaml
definitions:
  Model1:
    properties:
      N1:
        type: integer
    x-swagger-mongoose:
      additional-properties:
        N2:
          type: integer
```

```
TypeError: Undefined type `Integer` at `N2`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/obrian/projects/node_workspace/bc1/node_modules/mongoose/lib/schema.js:605:11)
    at Schema.path (/Users/obrian/projects/node_workspace/bc1/node_modules/mongoose/lib/schema.js:509:29)
    at Schema.add (/Users/obrian/projects/node_workspace/bc1/node_modules/mongoose/lib/schema.js:393:12)
    at new Schema (/Users/obrian/projects/node_workspace/bc1/node_modules/mongoose/lib/schema.js:96:10)
    at /Users/obrian/projects/node_workspace/bc1/node_modules/swagger-mongoose-fork/lib/index.js:323:20
    at /Users/obrian/projects/node_workspace/bc1/node_modules/swagger-mongoose-fork/node_modules/lodash/lodash.js:4411:15
    at baseForOwn (/Users/obrian/projects/node_workspace/bc1/node_modules/swagger-mongoose-fork/node_modules/lodash/lodash.js:2654:24)
    at /Users/obrian/projects/node_workspace/bc1/node_modules/swagger-mongoose-fork/node_modules/lodash/lodash.js:4380:18
    at Function.forEach (/Users/obrian/projects/node_workspace/bc1/node_modules/swagger-mongoose-fork/node_modules/lodash/lodash.js:8634:14)
    at Object.module.exports.compile (/Users/obrian/projects/node_workspace/bc1/node_modules/swagger-mongoose-fork/lib/index.js:300:5)
    at /Users/obrian/projects/node_workspace/bc1/app.js:47:23
    at /Users/obrian/projects/node_workspace/bc1/node_modules/swagger-express-mw/lib/index.js:32:5
    at /Users/obrian/projects/node_workspace/bc1/node_modules/swagger-node-runner/index.js:234:7
    at wrappedPromise.linkTransaction (/Users/obrian/projects/node_workspace/bc1/node_modules/newrelic/lib/instrumentation/core/globals.js:168:23)
    at wrappedPromise.wrapped (/Users/obrian/projects/node_workspace/bc1/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at wrappedPromise.proxyWrapper (/Users/obrian/projects/node_workspace/bc1/node_modules/newrelic/lib/instrumentation/core/globals.js:172:59)
/Users/obrian/projects/node_workspace/bc1/node_modules/swagger-node-runner/index.js:241
      process.nextTick(function() { throw err; });
                                    ^

TypeError: Undefined type `Integer` at `N2`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/obrian/projects/node_workspace/bc1/node_modules/mongoose/lib/schema.js:605:11)
    at Schema.path (/Users/obrian/projects/node_workspace/bc1/node_modules/mongoose/lib/schema.js:509:29)
    at Schema.add (/Users/obrian/projects/node_workspace/bc1/node_modules/mongoose/lib/schema.js:393:12)
    at new Schema (/Users/obrian/projects/node_workspace/bc1/node_modules/mongoose/lib/schema.js:96:10)
    at /Users/obrian/projects/node_workspace/bc1/node_modules/swagger-mongoose-fork/lib/index.js:323:20
    at /Users/obrian/projects/node_workspace/bc1/node_modules/swagger-mongoose-fork/node_modules/lodash/lodash.js:4411:15
    at baseForOwn (/Users/obrian/projects/node_workspace/bc1/node_modules/swagger-mongoose-fork/node_modules/lodash/lodash.js:2654:24)
    at /Users/obrian/projects/node_workspace/bc1/node_modules/swagger-mongoose-fork/node_modules/lodash/lodash.js:4380:18
    at Function.forEach (/Users/obrian/projects/node_workspace/bc1/node_modules/swagger-mongoose-fork/node_modules/lodash/lodash.js:8634:14)
    at Object.module.exports.compile (/Users/obrian/projects/node_workspace/bc1/node_modules/swagger-mongoose-fork/lib/index.js:300:5)
    at /Users/obrian/projects/node_workspace/bc1/app.js:47:23
    at /Users/obrian/projects/node_workspace/bc1/node_modules/swagger-express-mw/lib/index.js:32:5
    at /Users/obrian/projects/node_workspace/bc1/node_modules/swagger-node-runner/index.js:234:7
    at wrappedPromise.linkTransaction (/Users/obrian/projects/node_workspace/bc1/node_modules/newrelic/lib/instrumentation/core/globals.js:168:23)
    at wrappedPromise.wrapped (/Users/obrian/projects/node_workspace/bc1/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at wrappedPromise.proxyWrapper (/Users/obrian/projects/node_workspace/bc1/node_modules/newrelic/lib/instrumentation/core/globals.js:172:59)
```

**Comment by briananderson1222** [comment]
@AilisObrian would you like to submit your fix as a PR? @simonguest I can try and help with maintenance since I know you are not around much

**Comment by simonguest** [comment]
@briananderson1222 Sounds great - and thanks again for helping out. As I don't have enough bandwidth (and I'm spending more time with GraphQL these days vs. Swagger), I'll make you a committer to this repo.

**Comment by AilisObrian** [comment]
@briananderson1222 submitted! :)

**Comment by briananderson1222** [comment]
https://github.com/simonguest/swagger-mongoose/pull/24
